# Generated by Django 4.2.3 on 2023-08-17 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptno', models.IntegerField()),
                ('dname', models.CharField(max_length=100)),
                ('loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('Empno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Ename', models.CharField(max_length=100)),
                ('sal', models.IntegerField()),
                ('Hiredate', models.DateField()),
                ('Comm', models.IntegerField(null=True)),
                ('deptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
    ]
